import type { MenuItem, Order } from './types';

export const menuItems: MenuItem[] = [
  {
    id: '1',
    name: 'Mumbai Vadapav',
    description: 'The classic and beloved street food from Mumbai.',
    price: 29.0,
    category: 'Vadapav',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '2',
    name: 'Mumbai Crispy Vadapav',
    description: 'A crispy twist on the classic Mumbai vadapav.',
    price: 29.0,
    category: 'Vadapav',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '3',
    name: 'Hatke Masala Vadapav',
    description: 'A special masala vadapav with a unique flavor.',
    price: 30.0,
    category: 'Vadapav',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '4',
    name: 'Hatke Jumbo Vadapav',
    description: 'A bigger, more filling version of our signature vadapav.',
    price: 34.0,
    category: 'Vadapav',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '5',
    name: 'Hatke Peri Peri Vadapav',
    description: 'A spicy and tangy peri peri flavored vadapav.',
    price: 34.0,
    category: 'Vadapav',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '6',
    name: 'Hatke Janjhanit Vadapav',
    description: 'An extra spicy vadapav for those who love the heat.',
    price: 34.0,
    category: 'Vadapav',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '7',
    name: 'Hatke Tandoori Vadapav',
    description: 'Vadapav with a smoky tandoori flavor.',
    price: 34.0,
    category: 'Vadapav',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '8',
    name: 'Hatke Cheese & Onion Vadapav',
    description: 'A delicious combination of cheese and onion in a vadapav.',
    price: 34.0,
    category: 'Vadapav',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '9',
    name: 'Hatke VIP Vadapav',
    description: 'Our special, premium vadapav.',
    price: 34.0,
    category: 'Vadapav',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '10',
    name: 'Sabudana Vada (2 Piece)',
    description: 'Crispy vadas made from tapioca pearls.',
    price: 40.0,
    category: 'Vadapav',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '11',
    name: 'Veg Burger',
    description: 'A classic vegetarian burger.',
    price: 55.0,
    category: 'Burger',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '12',
    name: 'Peri Peri Burger',
    description: 'A spicy burger with peri peri sauce.',
    price: 55.0,
    category: 'Burger',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '13',
    name: 'Mexican Burger',
    description: 'A burger with a zesty Mexican twist.',
    price: 55.0,
    category: 'Burger',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '14',
    name: 'Chatpata Burger',
    description: 'A tangy and spicy burger.',
    price: 55.0,
    category: 'Burger',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '15',
    name: 'Tandoori Burger',
    description: 'A burger with smoky tandoori flavors.',
    price: 55.0,
    category: 'Burger',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '16',
    name: 'Italian Burger',
    description: 'A burger inspired by Italian flavors.',
    price: 55.0,
    category: 'Burger',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '17',
    name: 'Spicy Burger',
    description: 'For those who like it extra hot.',
    price: 55.0,
    category: 'Burger',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '18',
    name: 'Cheese & Onion Burger',
    description: 'A classic combination of cheese and onion.',
    price: 55.0,
    category: 'Burger',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '19',
    name: 'Corn Burger',
    description: 'A burger with a sweet corn patty.',
    price: 55.0,
    category: 'Burger',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '20',
    name: 'Crispy Burger',
    description: 'A burger with an extra crispy patty.',
    price: 60.0,
    category: 'Burger',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '21',
    name: 'Paneer Masala Burger',
    description: 'A burger with a flavorful paneer masala patty.',
    price: 70.0,
    category: 'Burger',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '22',
    name: 'Veg Pizza',
    description: 'A delicious pizza with fresh vegetable toppings.',
    price: 109.0,
    category: 'Pizza',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '23',
    name: 'Corn Pizza',
    description: 'A pizza topped with golden sweet corn.',
    price: 109.0,
    category: 'Pizza',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '24',
    name: 'Paneer Pizza',
    description: 'A pizza with savory paneer toppings.',
    price: 115.0,
    category: 'Pizza',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '25',
    name: 'Italian Pizza',
    description: 'An authentic pizza with Italian herbs and toppings.',
    price: 115.0,
    category: 'Pizza',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '26',
    name: 'Cheese Corn Roll',
    description: 'A warm roll filled with melted cheese and sweet corn.',
    price: 75.0,
    category: 'Roll',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '27',
    name: 'Paneer Tikki Roll',
    description: 'A delicious roll with a paneer tikki filling.',
    price: 65.0,
    category: 'Roll',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '28',
    name: 'Chole Roll',
    description: 'A hearty roll with a spicy chole filling.',
    price: 55.0,
    category: 'Roll',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '29',
    name: 'Salted French Fries',
    description: 'Classic, crispy, and perfectly salted french fries.',
    price: 49.0,
    category: 'Fries',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '30',
    name: 'Peri Peri Fries Chilly',
    description: 'Fries tossed in a spicy and tangy peri peri seasoning.',
    price: 59.0,
    category: 'Fries',
    imageUrl: 'https://placehold.co/300x200.png',
  },
  {
    id: '31',
    name: 'Chatpata Fries',
    description: 'Fries with a tangy and savory chatpata flavor.',
    price: 59.0,
    category: 'Fries',
    imageUrl: 'https://placehold.co/300x200.png',
  },
];

export const orders: Order[] = [];

// Simulate fetching data
export const getMenuItems = async (): Promise<MenuItem[]> => {
  return new Promise((resolve) => setTimeout(() => resolve(menuItems), 500));
};

export const getOrders = async (): Promise<Order[]> => {
  return new Promise((resolve) => setTimeout(() => resolve(orders), 500));
};
